name: linting

on:
  push:
  workflow_dispatch:

jobs:
  linting:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Install dependencies
        run: pip install ruff

      - name: Run linter
        run: ruff check .


